In [99]:
import pandas as pd

In [100]:
censo = pd.read_csv('data/adult.csv')

In [101]:
censo.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [102]:
censo.describe()

,age,final-weight,education-num,capital-gain,capital-loos,hour-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [103]:
previsores = censo.iloc[:,:14].values
classe = censo.iloc[:,14].values

# Tansformação de Variaveis categoricas para numericas

In [104]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [105]:
label_encoder_previsores = LabelEncoder()

In [106]:
#labels = label_encoder_previsores.fit_transform(previsores[:,1])

In [107]:
previsores[:,1] = label_encoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = label_encoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = label_encoder_previsores.fit_transform(previsores[:,5])
previsores[:,6] = label_encoder_previsores.fit_transform(previsores[:,6])
previsores[:,7] = label_encoder_previsores.fit_transform(previsores[:,7])
previsores[:,8] = label_encoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = label_encoder_previsores.fit_transform(previsores[:,9])
previsores[:,13] = label_encoder_previsores.fit_transform(previsores[:,13])

In [115]:
label_encoder_classe = LabelEncoder()
classe = label_encoder_classe.fit_transform(classe)

In [108]:
pd.DataFrame(previsores)

        0  1       2   3   4  5   6  7  8  9     10 11  12  13
0      39  7   77516   9  13  4   1  1  4  1   2174  0  40  39
1      50  6   83311   9  13  2   4  0  4  1      0  0  13  39
2      38  4  215646  11   9  0   6  1  4  1      0  0  40  39
3      53  4  234721   1   7  2   6  0  2  1      0  0  40  39
4      28  4  338409   9  13  2  10  5  2  0      0  0  40   5
...    .. ..     ...  ..  .. ..  .. .. .. ..    ... ..  ..  ..
32556  27  4  257302   7  12  2  13  5  4  0      0  0  38  39
32557  40  4  154374  11   9  2   7  0  4  1      0  0  40  39
32558  58  4  151910  11   9  6   1  4  4  0      0  0  40  39
32559  22  4  201490  11   9  4   1  3  4  1      0  0  20  39
32560  52  5  287927  11   9  2   4  5  4  0  15024  0  40  39

[32561 rows x 14 columns]

# Tansformação de Variaveis Categoricas com OneHotEncoder

## No algoritimo anterior, ele havia um certo Preconceito, pois ele iria considerar a raça por pesos ex: black: 2 White :1 , ele iria considerar o preto melhor que o branco, entao abordaremos de outra forma

In [109]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer 

ct = ColumnTransformer([("Country", OneHotEncoder(), [1,3,5,6,7,8,9,13])],    remainder = 'passthrough')
previsores = ct.fit_transform(previsores).todense()

In [111]:
pd.DataFrame(previsores)

,0,1,2,3,4,5,6,7,8,9,...,98,99,100,101,102,103,104,105,106,107
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,39.0,77516.0,13.0,2174.0,0.0,40.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,50.0,83311.0,13.0,0.0,0.0,13.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,38.0,215646.0,9.0,0.0,0.0,40.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,53.0,234721.0,7.0,0.0,0.0,40.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,28.0,338409.0,13.0,0.0,0.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,27.0,257302.0,12.0,0.0,0.0,38.0
32557,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,40.0,154374.0,9.0,0.0,0.0,40.0
32558,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,58.0,151910.0,9.0,0.0,0.0,40.0
32559,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,22.0,201490.0,9.0,0.0,0.0,20.0
32560,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,52.0,287927.0,9.0,15024.0,0.0,40.0

# Escalonamento de Atributos

In [116]:
from sklearn.preprocessing import StandardScaler

In [122]:
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

In [124]:
pd.DataFrame(previsores)

,0,1,2,3,4,5,6,7,8,9,...,98,99,100,101,102,103,104,105,106,107
0,-0.24445,-0.174295,-0.262097,-0.014664,-1.516792,-0.188389,-0.290936,4.907700,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,-0.24445,-0.174295,-0.262097,-0.014664,-1.516792,-0.188389,3.437186,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,-2.932948,-0.045408,-0.022173,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,-0.849080,0.639741,0.746039,-0.145920,-0.21666,-0.197409
32557,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,0.103983,-0.335433,-0.420060,-0.145920,-0.21666,-0.035429
32558,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,1.423610,-0.358777,-0.420060,-0.145920,-0.21666,-0.035429
32559,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,-1.215643,0.110960,-0.420060,-0.145920,-0.21666,-1.655225
32560,-0.24445,-0.174295,-0.262097,-0.014664,-1.516792,5.308156,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,0.983734,0.929893,-0.420060,1.888424,-0.21666,-0.035429

In [125]:
from sklearn.model_selection import train_test_split

In [126]:
X_train, X_test, y_train, y_test = train_test_split(previsores,classe,test_size=0.25,random_state=0)